<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Runubala" failures="1" tests="5" name="AlwaysRun_Demo" time="0.057" errors="0" timestamp="2022-09-12T23:02:53 IST">
  <testcase classname="com.nt.partice.AlwaysRun_partice" name="Begin" time="0.002">
    <failure type="java.lang.AssertionError" message="We are failing the testcase">
      <![CDATA[java.lang.AssertionError: We are failing the testcase
at com.nt.partice.AlwaysRun_partice.Begin(AlwaysRun_partice.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- Begin -->
  <testcase classname="com.nt.partice.AlwaysRun_partice" name="Ready" time="0.002"/>
  <testcase classname="com.nt.partice.AlwaysRun_partice" name="Steady" time="0.002"/>
  <testcase classname="com.nt.partice.AlwaysRun_partice" name="Running" time="0.002"/>
  <testcase classname="com.nt.partice.AlwaysRun_partice" name="End" time="0.0">
    <skipped/>
  </testcase> <!-- End -->
</testsuite> <!-- AlwaysRun_Demo -->
